name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id:
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Others
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Are you interested in contributing?
      options:
        - label: I'd like to work on this issue
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/digitomize/digitomize/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I have used the search function to check if an issue already exists
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: dropdown
    id: program
    validations:
      required: true
    attributes:
      label: Which program are you contributing in?
      options: ['Not applicable','gssoc', 'swoc', 'kwoc', 'dwoc', 'tublian', 'ssoc']
      multiple: true
