---
name: 🛠️ Feature Request
description: Suggest an idea to help us improve digitomize.
title: "[Feature]: "
labels:
  - "feature_request"

body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request report!**
        We kindly ask that you search to see if an issue [already exists](https://github.com/digitomize/digitomize/issues) for your feature.

        We are also happy to accept contributions from our users. For more details see [here](https://github.com/digitomize/digitomize/blob/main/CONTRIBUTING.md)

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: |
        A clear and concise description of the feature you're interested in.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
       A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Describe alternatives you've considered.
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false