import BgEllipse from './BgEllipse';
import Button from './Button';
import Card from './Card';
import Contests from './Contests';
import CopyToClipboard from './CopyToClipboard';
import ErrorPage from './error-page';
import Feedback from './Feedback';
import Home from './Home';
import HomePage1 from './HomePage1';
import HomePage2 from './HomePage2';
import IndividualCard from './IndividualCard';
import Layout from './Layout';
import Login from './Login';
import Logout from './Logout';
import MobNav from './MobNav';
import Navbar from './Navbar';
import NewHome from './NewHome';
import NewFooter from './NewFooter';
import NewLogin from './NewLogin';
import  { loader as loginLoader } from "./Login" ;
import  { loader as signupLoader } from "./Signup" ;
import NewNavbar from './NewNavbar';
import ScrollToTop from './ScrollToTop';
import Signup from './Signup';
import Updates from './Updates';
export { BgEllipse, Button, Card, Contests, CopyToClipboard, ErrorPage, Feedback, Home, HomePage1, HomePage2, IndividualCard, Layout, Login, Logout, MobNav, Navbar, NewHome, NewFooter, NewLogin, NewNavbar, ScrollToTop, Signup, Updates,loginLoader,signupLoader }