name: "PR Title Checker"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR Title Format
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pattern = /^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|temp)\: .*/;
            const title = github.event.pull_request.title;
            if (!pattern.test(title)) {
              const errorMessage = "Error: PR title does not conform to the required format. Please use one of the specified prefixes followed by a colon and a space.";
              console.error(errorMessage);
              core.setFailed(errorMessage);
            }
